# Token reminder: github > settings > developer > > tokens > (re)generate > copy on clipoard
# On travis: assign the clipboard to GH_REPO_TOKEN
language: sh

# latest distribution
# https://docs.travis-ci.com/user/reference/overview/
dist: focal

# just master branch (verify branch name)
branches:
  only:
    - master

# install dependencies
addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - zsh
      - environment-modules

# environment must be defined
# one build will be triggered for each line in the env array.
env:
  - TRAVISENVIRONMENT=yes

# scripts to execute
script:
 - ./makeDoxy.sh
 - ./testLibraries.sh

# generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doxygen
  github_token: $GH_REPO_TOKEN
  on:
    branch: master

