# Token reminder: github > settings > developer > generate > copy on clipoard
# On travis: assign the clipboard to GH_REPO_TOKEN
language: sh

# latest distribution
# https://docs.travis-ci.com/user/reference/overview/
dist: focal

# just main branch
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - zsh
      - environment-modules

# scripts to execute
script:
 - ./makeDoxy.sh
 - ./testLibraries.sh

# Generate and deploy documentation
#
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doxygen
  github_token: $GH_REPO_TOKEN
  on:
    branch: master

